import {
  esc, getTimestamp, baseStyles, headerHTML, formatCurrency,
} from "@/components/parts/print/printHelpers";
import { getCategoryPathLabel } from "@/lib/categoryTreeHelpers";
import {
  renderIllustratedCard, illustratedCSS,
  renderPriceListRow, renderPriceListHeader, priceListCSS,
  renderSummaryRow, renderSummaryHeader, summaryCSS,
  renderSectionHeading,
} from "@/components/parts/print/sharedPrintRenderers";

/**
 * Builds a print-ready HTML report for a single Parts Group.
 * Uses shared renderers from sharedPrintRenderers.js for visual parity with Parts Catalog.
 */
export function buildPartGroupPrintHTML({
  group, enrichedItems, sections, summary, vendorsMap,
  inventoryViewMap, catLookups,
  reportType = "summary", printOptions = {},
}) {
  const ts = getTimestamp();
  const opts = printOptions || {};
  const groupReportBy = opts.groupReportBy || "section";

  // Report type label for header
  const reportLabel = {
    summary: "Summary Report",
    illustrated: "Illustrated Catalog",
    priceList: "Price List",
    compact: "Compact List",
  }[reportType] || "Parts Group";

  const subtitle = [
    group.name,
    group.group_code ? `Code: ${group.group_code}` : null,
    group.category || null,
    group.status,
  ].filter(Boolean).join(" · ");

  // Summary strip
  const stripHTML = `<div class="summary-strip">
    <span>Parts: <strong>${summary.uniqueParts}</strong></span>
    <span>Total Qty: <strong>${summary.totalQty}</strong></span>
    <span>Required: <strong>${summary.requiredCount}</strong></span>
    <span>Optional: <strong>${summary.optionalCount}</strong></span>
    <span>Required Est: <strong>${formatCurrency(summary.requiredCost)}</strong></span>
    <span>Optional Est: <strong>${formatCurrency(summary.optionalCost)}</strong></span>
    <span>Total Est: <strong>${formatCurrency(summary.totalCost)}</strong></span>
  </div>`;

  const descHTML = group.description
    ? `<div style="margin-bottom:12px;font-size:9pt;color:#444;max-width:80ch;">${esc(group.description)}</div>`
    : "";

  const instrHTML = group.instructions
    ? `<div style="margin-bottom:12px;padding:8px;background:#f0f7ff;border:1px solid #c8ddf5;border-radius:4px;font-size:8.5pt;color:#333;"><strong>Instructions:</strong> ${esc(group.instructions)}</div>`
    : "";

  // Build sections from enrichedItems
  const reportSections = buildReportSections(enrichedItems, groupReportBy, catLookups);

  // Normalize items to shared PrintPart model
  const normalizePart = (item) => {
    const { part, inv, unitCost, extCost } = item;
    const vendor = vendorsMap?.[part.default_vendor_id];
    const catPath = part.part_category_id && catLookups?.byId?.[part.part_category_id]
      ? getCategoryPathLabel(part.part_category_id, catLookups.byId) : "";
    const retail = part.retail_override || part.retail_matrix_price || 0;
    return {
      id: part.id,
      name: part.part_name,
      partNumber: part.vendor_part_number,
      image: part.featured_photo || part.photos?.[0] || null,
      categoryPath: catPath,
      notes: part.notes,
      partType: part.part_type,
      source: vendor?.vendor_name || null,
      cost: unitCost,
      retail,
      stock: inv?.physical_stock ?? null,
      demand: inv?.required_total ?? null,
      extCost: extCost,
      extRetail: retail * (item.quantity || 1),
      quantity: item.quantity || 1,
      requiredOptional: item.is_optional ? "Optional" : "Required",
      groupNotes: item.notes || null,
    };
  };

  let bodyHTML = "";
  let reportCSS = "";

  if (reportType === "illustrated") {
    reportCSS = illustratedCSS();
    bodyHTML = buildIllustratedBody(reportSections, opts, normalizePart);
  } else if (reportType === "priceList") {
    reportCSS = priceListCSS();
    bodyHTML = buildPriceListBody(reportSections, opts, normalizePart);
  } else if (reportType === "compact") {
    reportCSS = summaryCSS();
    bodyHTML = buildCompactBody(reportSections, opts, catLookups, enrichedItems);
  } else {
    reportCSS = summaryCSS();
    bodyHTML = buildSummaryBody(reportSections, opts, normalizePart, groupReportBy);
  }

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><title>${esc(group.name)} — ${esc(reportLabel)}</title>
<style>
  ${baseStyles()}
  ${reportCSS}
</style>
</head><body>
  ${headerHTML(reportLabel, subtitle, null, ts)}
  ${descHTML}
  ${instrHTML}
  ${stripHTML}
  ${bodyHTML}
  <div class="estimate-note">* Estimated costs based on current Parts Tracker cost data. Actual costs may vary.</div>
  ${groupFooterHTML(ts)}
</body></html>`;
}

function groupFooterHTML(ts) {
  return `<div class="footer">
    <span>Generated by AK Projects — Parts Groups</span>
    <span>${esc(ts.dateStr)} ${esc(ts.timeStr)}</span>
  </div>`;
}

function buildReportSections(enrichedItems, groupReportBy, catLookups) {
  if (groupReportBy === "category") {
    const map = new Map();
    for (const item of enrichedItems) {
      const catId = item.part?.part_category_id;
      const label = catId && catLookups?.byId?.[catId]
        ? getCategoryPathLabel(catId, catLookups.byId) : "Uncategorized";
      if (!map.has(label)) map.set(label, []);
      map.get(label).push(item);
    }
    return Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b));
  }
  if (groupReportBy === "none") {
    return [["All Parts", enrichedItems]];
  }
  const sectionMap = new Map();
  for (const item of enrichedItems) {
    const section = item.section_name || "General Parts";
    if (!sectionMap.has(section)) sectionMap.set(section, []);
    sectionMap.get(section).push(item);
  }
  return Array.from(sectionMap.entries());
}

// ─── ILLUSTRATED (uses shared full-width card) ──────────────────────────
function buildIllustratedBody(sections, opts, normalizePart) {
  let html = "";
  for (const [sectionName, sectionItems] of sections) {
    if (sections.length > 1) {
      html += renderSectionHeading(sectionName, sectionItems.length);
    }
    for (const item of sectionItems) {
      html += renderIllustratedCard(normalizePart(item), {
        includeImages: opts.includeImages !== false,
        includeNotes: opts.includeNotes !== false,
        includeCost: opts.includeCost !== false,
        includeSource: opts.includeSource !== false,
        isGroupContext: true,
      });
    }
  }
  return html;
}

// ─── PRICE LIST (uses shared table rows) ────────────────────────────────
function buildPriceListBody(sections, opts, normalizePart) {
  let html = "";
  let globalIdx = 0;
  for (const [sectionName, sectionItems] of sections) {
    if (sections.length > 1) {
      html += renderSectionHeading(sectionName, sectionItems.length);
    }
    html += renderPriceListHeader({
      includeImages: !!opts.includeImages,
      isGroupContext: true,
    });
    for (const item of sectionItems) {
      globalIdx++;
      html += renderPriceListRow(normalizePart(item), globalIdx, {
        includeImages: !!opts.includeImages,
        includeDescriptions: !!opts.includeDescriptions,
        isGroupContext: true,
      });
    }
    html += `</tbody></table>`;
  }
  return html;
}

// ─── SUMMARY (uses shared table rows) ───────────────────────────────────
function buildSummaryBody(sections, opts, normalizePart, groupReportBy) {
  let html = "";
  let globalIdx = 0;
  const showCategory = groupReportBy !== "category";

  for (const [sectionName, sectionItems] of sections) {
    const sectionCost = sectionItems.reduce((s, i) => s + i.extCost, 0);
    if (sections.length > 1) {
      html += `<div class="subcategory-group">`;
      html += renderSectionHeading(sectionName, sectionItems.length, formatCurrency(sectionCost));
    }

    html += renderSummaryHeader({
      includeCost: opts.includeCost !== false,
      includeRetail: !!opts.includeRetail,
      includeSource: opts.includeSource !== false,
      includeStock: opts.includeStock !== false,
      includeDemand: opts.includeDemand !== false,
      includeNotes: opts.includeNotes !== false,
      isGroupContext: true,
      showCategory,
    });

    for (const item of sectionItems) {
      globalIdx++;
      const p = normalizePart(item);
      if (showCategory) p._showCategory = true;
      html += renderSummaryRow(p, globalIdx, {
        includeCost: opts.includeCost !== false,
        includeRetail: !!opts.includeRetail,
        includeSource: opts.includeSource !== false,
        includeStock: opts.includeStock !== false,
        includeDemand: opts.includeDemand !== false,
        includeNotes: opts.includeNotes !== false,
        isGroupContext: true,
      });
    }
    html += `</tbody></table>`;
    if (sections.length > 1) html += `</div>`;
  }
  return html;
}

// ─── COMPACT LIST (group-specific, no catalog equivalent) ───────────────
function buildCompactBody(sections, opts, catLookups, enrichedItems) {
  let html = "";
  let globalIdx = 0;
  for (const [sectionName, sectionItems] of sections) {
    if (sections.length > 1) {
      html += renderSectionHeading(sectionName, sectionItems.length);
    }
    html += `<table class="parts-table compact-table"><thead><tr>
      <th class="col-num">#</th>
      <th>Part Name</th>
      ${opts.includePartNumber !== false ? '<th>Part #</th>' : ''}
      ${opts.includeCategory !== false ? '<th>Category</th>' : ''}
      <th style="text-align:center">Qty</th>
      <th>Req/Opt</th>
    </tr></thead><tbody>`;
    for (const item of sectionItems) {
      globalIdx++;
      const { part } = item;
      const catPath = opts.includeCategory !== false && part.part_category_id && catLookups?.byId?.[part.part_category_id]
        ? getCategoryPathLabel(part.part_category_id, catLookups.byId) : "";
      html += `<tr class="${globalIdx % 2 === 0 ? "even" : "odd"}">
        <td class="num">${globalIdx}</td>
        <td><div class="part-name">${esc(part.part_name)}</div></td>
        ${opts.includePartNumber !== false ? `<td class="part-num">${part.vendor_part_number ? esc(part.vendor_part_number) : "—"}</td>` : ''}
        ${opts.includeCategory !== false ? `<td class="small" style="max-width:160px;word-wrap:break-word;">${catPath ? esc(catPath) : "—"}</td>` : ''}
        <td class="center qty">${item.quantity || 1}</td>
        <td class="small">${item.is_optional ? '<span style="color:#b45309;">Optional</span>' : "Required"}</td>
      </tr>`;
    }
    html += `</tbody></table>`;
  }
  return html;
}